### ISSUE TITLE
armeabi v7 出错

### ISSUE THREAD

**Issue by frank86225383** [troyzhao/MAME4Mobile#3]
armeabi v7 中的libMAME4droid.so 是不是有问题？我在android4.3的机子上跑会出错。

**Comment by troyzhao** [comment]
贴下报错信息

**Comment by frank86225383** [comment]
这是在编译armeabi-v7a 的so时报的错：
![image](https://user-images.githubusercontent.com/1931541/77321238-d5cac800-6d4c-11ea-9388-242c940a00ba.png)
我的编译环境是mac 64位操作系统，是否64位有关系？烦请帮忙解答下！

**Comment by frank86225383** [comment]
使用cpu类型是armeabi-v7a的设备跑时，报如下错误：
![image](https://user-images.githubusercontent.com/1931541/77324464-c26e2b80-6d51-11ea-85fb-78d990b3060c.png)

用的是你项目中编译的libMAME4droid.so 包。
帮忙看下是什么问题

**Comment by troyzhao** [comment]
> 这是在编译armeabi-v7a 的so时报的错：
> ![image](https://user-images.githubusercontent.com/1931541/77321238-d5cac800-6d4c-11ea-9388-242c940a00ba.png)
> 我的编译环境是mac 64位操作系统，是否64位有关系？烦请帮忙解答下！

这个错误看上去好像makefile写的不对啊 

<img width="392" alt="image" src="https://user-images.githubusercontent.com/3151615/77442712-8c9a7700-6e25-11ea-9684-8a8482cbfd54.png">

**Comment by troyzhao** [comment]
> 使用cpu类型是armeabi-v7a的设备跑时，报如下错误：
> ![image](https://user-images.githubusercontent.com/1931541/77324464-c26e2b80-6d51-11ea-85fb-78d990b3060c.png)
> 
> 用的是你项目中编译的libMAME4droid.so 包。
> 帮忙看下是什么问题

从AS里看下最终的apk里面libs是不是全的

**Comment by frank86225383** [comment]
> > 使用cpu类型是armeabi-v7a的设备跑时，报如下错误：
> > ![image](https://user-images.githubusercontent.com/1931541/77324464-c26e2b80-6d51-11ea-85fb-78d990b3060c.png)
> > 用的是你项目中编译的libMAME4droid.so 包。
> > 帮忙看下是什么问题
> 
> 从AS里看下最终的apk里面libs是不是全的

libs下面只有armeabi-v7a目录，目录下的.so是全的。

**Comment by wujiaqaz** [comment]
在4.3系统上运行遇到同样的问题，请问解决了吗

**Comment by troyzhao** [comment]
try this solution #4 , Contact me if it not work. (QQ: 410287161 )
